// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALq7BMpadS9X95KfUh8pJap1MYOXmBXds',
    appId: '1:1074295223145:web:81a80764549c7e290243f8',
    messagingSenderId: '1074295223145',
    projectId: 'scenickazatva-343517',
    authDomain: 'scenickazatva-343517.firebaseapp.com',
    databaseURL: 'https://scenickazatva-343517-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scenickazatva-343517.appspot.com',
    measurementId: 'G-G1RTZ98YKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgHwxABEwAc3qbxd_mBtebYfVZO2X6nkE',
    appId: '1:1074295223145:android:b0c4202e2ccb15d70243f8',
    messagingSenderId: '1074295223145',
    projectId: 'scenickazatva-343517',
    databaseURL: 'https://scenickazatva-343517-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scenickazatva-343517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBUnNiDz9AQQo9re021ECK2OJ92qAhOug',
    appId: '1:1074295223145:ios:94a31398c815d50b0243f8',
    messagingSenderId: '1074295223145',
    projectId: 'scenickazatva-343517',
    databaseURL: 'https://scenickazatva-343517-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scenickazatva-343517.appspot.com',
    iosClientId: '1074295223145-78ccho5aimjv9i9v6ek5i2paddoltof0.apps.googleusercontent.com',
    iosBundleId: 'sk.panakrala.scenickazatva',
  );
}
